### PR TITLE
W15-lab06 added md file

### PR DESCRIPTION
**Pull request by hannavigil**

### CODE REVIEW

**Comment by PazZaitGivon** [comment]
Hey, please make a new pull request to the appropriate branch asap remember you need to pull to the hannavigil branch

**Comment by PazZaitGivon** [comment]
also there is a bug with the implementation of edit. It will not receive full points and you are 75 points off the 500 to get full credit. To make my life easier when you repull please link to the issues you have completed or at least give me their names

**Comment by hannavigil** [comment]
Hey Paz,
I can't recreate the edit bug. It seems to work fine through my CSIL
account. Could you let me know how exactly you found the bug? Also, I think
we should be above the 500 pt mark. We did the deletion bug (100), javadoc
(25), delete all completed (100), sorting (125), edit (?), and saving and
loading from a file (200). I don't think you saw the last one though, or it
didn't work? I'll do a pull request with links as soon as we figure out the
edit issue.
Thanks,
Hanna

**Comment by PazZaitGivon** [comment]
ahh did not see the save and load from file. the bug ihappens I think if you add a task after editing?

**Comment by hannavigil** [comment]
Hey Paz,
Fixed the bug and made a new pull request. Hope I did it correctly this
time. Let me know if I did not.
Thanks,
Hanna

**Pull request closed without merging**
